[tool.black]
line-length = 80
exclude = '''
build/
| wheelhouse/
| dist/
| packages/
| \.hg/
| \.mypy_cache/
| \.venv/
| mercurial/thirdparty/
| hgext/fsmonitor/pywatchman/
| contrib/python-zstandard/
| contrib/grey.py
'''
skip-string-normalization = true
quiet = true
