#!/usr/bin/env python3
#
# mercurial - scalable distributed SCM
#
# Copyright 2005-2007 Olivia Mackall <olivia@selenic.com>
#
# This software may be used and distributed according to the terms of the
# GNU General Public License version 2 or any later version.

from __future__ import annotations

try:
    from mercurial import __main__
except ImportError:
    import sys

    msg = "abort: couldn't find mercurial libraries in [%s]"
    msg %= ' '.join(sys.path)

    print(msg, file=sys.stderr)
    print("(check your install and PYTHONPATH)\n", file=sys.stderr)
    sys.exit(-1)
else:
    __main__.run()
