edition = "2018"
max_width = 80
wrap_comments = true
error_on_line_overflow = true
imports_granularity = "Item"
group_imports = "StdExternalCrate"
use_small_heuristics = "Max"
single_line_if_else_max_width = 50
single_line_let_else_max_width = 50
