WHITESPACE = _{ " " | "\t" | "\r" | "\n" }

// `text` handles plain text outside substitutions; `string` handles quoted string
// literals inside substitutions, potentially with further nested substitutions.

// Octal escapes (e.g. `\000`) are not supported in the Rust parser.
text_escape  = @{
  "\\"
  ~ ("t" | "r" | "n" | ("0" ~ !ASCII_OCT_DIGIT) | "\\" | "'" | "\"" | "{")
}
text_content = @{ (!("{" | "\\") ~ ANY)+ }
text         = ${ (text_content | text_escape)+ }

string_quote   = _{ "'" | "\"" }
string_content = @{ (!(PEEK | "{" | "\\") ~ ANY)+ }
string         = _{ PUSH(string_quote) ~ (string_content | text_escape | substitution)* ~ POP }

raw_string_content = @{ ("\\" ~ PEEK | !PEEK ~ ANY)* }
raw_string         = _{ "r" ~ PUSH(string_quote) ~ raw_string_content ~ POP }

string_literal = ${ raw_string | string }

keyvalue      = { symbol ~ "=" ~ expr }
function_arg  = _{ keyvalue | expr }
function_args = { (function_arg ~ ("," ~ function_arg)*)? }
function      = { symbol ~ "(" ~ function_args ~ ")" }

integer  = @{ ASCII_DIGIT+ }
symbol   = @{ (ASCII_ALPHA | "_") ~ (ASCII_ALPHANUMERIC | "_")* }

negate_op = { "-" }
prefix_op = _{ negate_op }

dot_op   = { "." }
pipe_op  = { "|" }
list_op  = { "%" }
mul_op   = { "*" }
div_op   = { "/" }
add_op   = { "+" }
sub_op   = { "-" }
infix_op = _{
  dot_op
  | pipe_op
  | list_op
  | mul_op
  | div_op
  | add_op
  | sub_op
}

paren    = { "(" ~ expr ~ ")" }
primary  = _{ function | string_literal | integer | symbol | paren }
prefixed = _{ prefix_op* ~ primary }
expr     = { prefixed ~ (infix_op ~ prefixed)* }

substitution = !{ "{" ~ expr ~ "}" }

chunk    = _{ substitution | text }
template = ${ SOI ~ chunk* ~ EOI }
