# completion.py - utility to setup shell completion
#
# Copyright 2026 Octobus <contact@octobus.net>
#
# This software may be used and distributed according to the terms of the
# GNU General Public License version 2 or any later version.

from __future__ import annotations

import os

from ..i18n import _
from .. import (
    encoding,
    error,
    registrar,
    tables,
    util,
)
from ..utils import resourceutil

command = registrar.command(tables.command_table)


def init():
    """noop function that is called to make sure the module is loaded and has
    registered the necessary items.

    See `mercurial.initialization` for details"""


SHELLRC_MARKER = (
    b'# GENERATED BY "hg admin::setup-shell-completion" DO NOT EDIT'
)


def _setup_bash_completion(ui):
    """setup autocompletion for bash at the user level"""
    # write the completion script at the expected location
    script_path = os.path.join(
        b'~',
        b'.bash_completion',
        b'completions',
        b'hg',
    )

    setup_line = b'source "%s"' % script_path.replace(b'~', b'$HOME')
    _setup_comp_script(
        b"bash",
        b".bashrc",
        script_path,
        setup_line,
    )


def _setup_zsh_completion(ui):
    """setup autocompletion for zsh at the user level"""
    script_path = os.path.join(
        b'~',
        b'.local',
        b'share',
        b'zsh',
        b'site-functions',
        b'_hg',
    )
    setup_line = b'typeset -gaU fpath=($fpath "%s")'
    setup_line %= os.path.dirname(script_path.replace(b'~', b'$HOME'))
    _setup_comp_script(
        b"zsh",
        b".zshrc",
        script_path,
        setup_line,
        use_compinit=True,
    )


def _setup_tcsh_completion(ui):
    """setup autocompletion for tcsh at the user level"""
    script_path = os.path.join(
        b'~',
        b'.tcsh.d',
        b'completions',
        b'_hg',
    )
    setup_line = b'source "%s"' % script_path.replace(b'~', b'$HOME')
    _setup_comp_script(
        b"tcsh",
        b".cshrc",
        script_path,
        setup_line,
    )


def _setup_comp_script(
    shell: bytes,
    rcfile: bytes,
    script_path: bytes,
    setup_line: bytes,
    use_compinit: bool = False,
):
    """generic completion setup for shell

    - `shell` is the shell name used to retrieve the compresion script
    - `rcfile` is the name of the "rc" file for this shell in the user home
      directory.
    - `script_path` define where the completion script should be written
    - `setup_line` is the instruction that needs to be written to the "rc" file
      to enable the completion
    - `use_compinit` is used by "zsh" only.

    """
    script_path = util.expandpath(script_path)
    util.makedirs(os.path.dirname(script_path))
    with open(script_path, 'wb') as fp:
        script = _get_compl_script(shell)
        fp.write(script)
    # make sure it is imported in shell config
    gen_line = b'%s %s\n' % (setup_line, SHELLRC_MARKER)
    rc_path = util.expandpath(os.path.join(b"~", rcfile))
    try:
        with open(rc_path, "br") as fp:
            current_lines = list(fp)
    except FileNotFoundError:
        current_lines = []

    inserted = False
    next_lines = []
    for line in current_lines:
        if line.rstrip().endswith(SHELLRC_MARKER):
            if not inserted:
                next_lines.append(gen_line)
                inserted = True
        else:
            if use_compinit and b"compinit" in line and not inserted:
                next_lines.append(gen_line)
                inserted = True
            next_lines.append(line)
    if not inserted:
        next_lines.append(gen_line)
        if use_compinit:
            # also setup completion
            next_lines.append(b"autoload -u compinit\n")
            next_lines.append(b"compinit\n")
    next_content = b''.join(next_lines)
    with util.atomictempfile(rc_path, b"wb") as fp:
        fp.write(next_content)


def _get_compl_script(shell: bytes):
    pkg = b"mercurial.shell_completion"
    with resourceutil.open_resource(pkg, shell) as fp:
        return fp.read()


_SUPPORTED_COMPLETION = {
    b"bash": _setup_bash_completion,
    b"tcsh": _setup_tcsh_completion,
    b"zsh": _setup_zsh_completion,
}


@command(
    b'admin::setup-shell-completion',
    [
        (b'', b'list', None, _(b'list currently supported shells')),
        (b'', b'show-script', None, _(b'only display the completion script')),
        (
            b'',
            b'shell',
            b'',
            _(
                b"the shell for the completions to setup "
                b"(defaults to the current shell)"
            ),
            _(b'SHELL_NAME'),
        ),
    ],
    helpcategory=command.CATEGORY_MAINTENANCE,
    norepo=True,
)
def admin_setup_completion(ui, **opts):
    """Setup shell auto-completion for the current user

    The completion definition will be written in the user home directory and
    the shell "rc" file will be updated to make sure they are loaded.

    It is safe to call this command multiple time, it will update the
    completion definition to the latest version and not clutter the shell "rc"
    script.

    Use --list to see the supported shell.

    """
    if opts.get('list'):
        for s in sorted(_SUPPORTED_COMPLETION):
            shell_line = b'%s\n' % s
            ui.write(shell_line)
        return 0

    shell = opts.get('shell')
    if not shell:
        shell = os.path.basename(encoding.environ.get(b'SHELL', b"unknown"))

    if shell not in _SUPPORTED_COMPLETION:
        msg = _(b"no completion available for shell: %s") % shell
        raise error.InputError(msg)

    if opts.get('show_script'):
        script = _get_compl_script(shell)
        ui.write(script)
    else:
        _SUPPORTED_COMPLETION[shell](ui)
    return 0
